version: "3.1"

services:
  postgres_db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: "ProjBackTeste_DB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"