services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "ProjBackTesteDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"